version: '2.3'

services:
  statping:
    container_name: statping
    image: docker.wuenscheonline.de/statping/statping:v0.90.71.1
    #statping:v0.90.72
    #statping/statping:latest
    #restart: never
    #always
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8080:8080

volumes:
  statping_data:
